### ISSUE TITLE
2.0.0 release, please?

### ISSUE THREAD

**Issue by jvanasco** [formencode/formencode#140]
2.0.0.a1 has been around for a while. it would be nice to have a non-alpha release so package managers can install it as >=2.0.0

**Comment by brondsem** [comment]
Are any maintainers interested in keeping formencode going?  At least to keep it usable with current python versions, not necessarily looking for new feature development.  I would be willing to review & merge some of the current merge requests and make a pypi release, if the maintainers wanted to add me as a maintainer.  Otherwise I might make a fork, simply to put together the outstanding fixes.

Examples: #144 is an important fix for python3.  #153 and #155 look important for future python/setuptools releases.  And several other merge requests that look good safe housekeeping.

**Comment by jvanasco** [comment]
Have you forked this yet?  

I run a patched version on our own systems, but I have an opensource project that needs a fix to #144.

**Comment by lambacck** [comment]
2.0.0 is released.
