### ISSUE TITLE
tests appear to be broken, or at least undocumented.

### ISSUE THREAD

**Issue by jvanasco** [formencode/formencode#82]
The tests appear to be broken.  This might be covered by some ToDo.txt items, I'm not sure.

• a first selection of unittest tests are runnable via `python setup.py test`.  all pass.
• a second selection of nosetest tests (for the validators?) seem to be available from the file `run-tests-generate-coverage-html`.  many seem to be out of data with current function names and fail.
• a third selection of tests don't seem to be called from anything, notably the `test_htmlfill.py` file.

**Comment by lambacck** [comment]
Tests are run through Tox. You should however also be able to run all the tests directly using nosetest.

**Comment by lambacck** [comment]
Looks like we should change the ```test_suite``` option in setup.py to ```nose.collector```.

**Comment by Cito** [comment]
* Some test modules, like the mentioned `test_htmlfill.py`, are not writtten for `unittest`, they need `nose` to run. So you need to run `python setup.py nosetests` instead of `python setup.py test` to run all tests.
* The `run-tests-generate-coverage-tests` script does not run additional tests, it just creates a coverage report as html.
* The `test_suite` option should not be changed - `nose.collector` is [deprecated](https://code.google.com/p/python-nose/issues/detail?id=219), `python setup.py nosetests` works perfectly well without it.
