### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by daryllstrauss** [formencode/formencode#93]
It looks like Pypi that you want to license the code as Python Software Foundation, but there's no license file. Can you add one?

**Comment by lambacck** [comment]
I'd actually like it to be licensed something other than PSF license but that decision was made long ago and before my time. I'll put adding a PSF license file on my todo list.

**Comment by lambacck** [comment]
I added a LICENSE.txt for the project using PSF which matches what is in the setup.py. This was a poor choice of license because many of its clauses are specific to Python. I'd like to convert to MIT, but I'm not sure if that is allowed per PSF license and I'm really not sure if I could get sign off from all contributors ever.

**Comment by daryllstrauss** [comment]
That would make sense to me too, but obviously up to you and the authors.

Thanks for making it explicit in the repo in any case.

Daryll

**Comment by lambacck** [comment]
License is now MIT.
